name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: [macOS-latest]
    steps:

      - name: Run docker
        run: |
          brew cask install docker
          open --background -a Docker
          /Applications/Docker.app/Contents/Resources/bin/docker run hello-world
