name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: [windows-latest]
    steps:

      - name: Run docker
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
          choco install docker-desktop
          choco install kind
          kind create cluster

