name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: [windows-latest]
    steps:
      - name: Install docker
        run: |
          docker version
      - name: Switch to Linux Containers
        working-directory: C:\Program Files\Docker\Docker
        run: |
         ./DockerCli.exe -SwitchDaemon
      - name: Check docker
        run: |
          docker info
      - name: Install kind
        run: |
          choco install kind
      - name: Create cluster
        run: |
          kind create cluster
