name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: [windows-latest]
    steps:
      - name: Switch to Linux Containers
        run: |
         [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
         Restart-Service docker
      - name: Check docker
        run: |
          docker info
      - name: Install kind
        run: |
          choco install kind
      - name: Create cluster
        run: |
          kind create cluster
